/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reserva.h"

int puestos[10][4];

int *
reservar_1_svc(puesto *argp, struct svc_req *rqstp)
{
	static int  result;
	static int cantidad;

	#ifndef PUESTOS_INICIADOS
	cantidad = 0;
	int fila = 0;
	int columna = 0;
	for(;fila<10;fila++) {
		for(;columna<4;columna++) {
			puestos[fila][columna] = 0;
		}
	}
	#endif
	#define PUESTOS_INICIADOS

	fila = argp->fila;
	columna = argp->columna;

	if(puestos[fila][columna] == 0) {
		puestos[fila][columna] = 1;
		++cantidad;
		result = 0;
	}
	else if(fila<0 || columna<0 || fila>9 || columna>3)
		result = 1;
	else if(puestos[fila][columna] == 1)
		result = 2;
	else if(cantidad == 40)
		result = 3;

	return &result;
}

char **
mostrar_disponibles_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	int i, j, n;

	result = (char*)malloc(sizeof(char)*40*2+1);

	n = 0;
	for(i=0;i<10;i++) {
		for(j=0;j<4;j++) {
			if(puestos[i][j] == 0) {
				result[n+1] = i+'0';
				result[n+2] = j+'0';
				n = n+2;
			}
		}
	}
	result[0] = n;

	return &result;
}
