/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "reserva.h"

bool_t
xdr_puesto (XDR *xdrs, puesto *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->fila))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->columna))
		 return FALSE;
	return TRUE;
}
