/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RESERVA_H_RPCGEN
#define _RESERVA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct puesto {
	int fila;
	int columna;
};
typedef struct puesto puesto;

#define RESERVA_PROG 0x31111111
#define RESERVA_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define RESERVAR 1
extern  int * reservar_1(puesto *, CLIENT *);
extern  int * reservar_1_svc(puesto *, struct svc_req *);
#define MOSTRAR_DISPONIBLES 2
extern  char ** mostrar_disponibles_1(void *, CLIENT *);
extern  char ** mostrar_disponibles_1_svc(void *, struct svc_req *);
extern int reserva_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RESERVAR 1
extern  int * reservar_1();
extern  int * reservar_1_svc();
#define MOSTRAR_DISPONIBLES 2
extern  char ** mostrar_disponibles_1();
extern  char ** mostrar_disponibles_1_svc();
extern int reserva_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_puesto (XDR *, puesto*);

#else /* K&R C */
extern bool_t xdr_puesto ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RESERVA_H_RPCGEN */
