/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "reserva.h"


void
reserva_prog_1(char *host, int fila, int columna)
{
	CLIENT *clnt;
	int  *result_1;
	puesto  reservar_1_arg;
	char * *result_2;
	char *mostrar_disponibles_1_arg;

	reservar_1_arg.fila = fila;
	reservar_1_arg.columna = columna;


#ifndef	DEBUG
	clnt = clnt_create (host, RESERVA_PROG, RESERVA_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = reservar_1(&reservar_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else if(*result_1 == 0) {
		printf("Puesto %d %d reservado\n", fila, columna);
	}
	else if(*result_1 == 1) {
		fprintf(stderr, "El puesto pedido no esta en el rango valido\n");
		exit(1);
	}
	else if(*result_1 == 2) {
		result_2 = mostrar_disponibles_1((void*)&mostrar_disponibles_1_arg, clnt);
		if (result_2 == (void *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		int n = **result_2;
		int i;
		printf("Asientos disponibles %d: <fila, columna>\n", n/2);
		for(i=1; i<n; i=i+2) {
			printf("<%c, %c>\n", result_2[0][i], result_2[0][i+1]);
		}
	}
	else if(*result_1 == 3) {
		printf("El vagon esta full\n");
		exit(3);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int fila, columna;

	if (argc < 4) {
		printf ("usage: %s servidor fila columna\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	fila = atoi(argv[2]);
	columna = atoi(argv[3]);

	reserva_prog_1 (host, fila, columna);
exit (0);
}
